nelmio_cors:
    defaults:
        allow_credentials: false
        allow_headers: ['*']
        expose_headers: ['*']
        max_age: 0
        hosts: ['*']
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:5173']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://127.0.0.1:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
            max_age: 3600
            hosts: ['^api\.']